#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

In [2]:
!pip show numpy

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /home/abdurrehman/anaconda3/lib/python3.9/site-packages
Requires: 
Required-by: astropy, bkcharts, bokeh, Bottleneck, daal4py, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tifffile, xarray


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)

In [4]:
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)


In [5]:
null_vector.itemsize

8

In [6]:
null_vector.nbytes

80

In [7]:
arr= np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr.itemsize

8

In [9]:
arr.nbytes

72

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
null_vector[4]= 1

In [13]:
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
arr7 = np.arange(10,49)

In [15]:
arr7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
arr8 = np.array([1,2,3,4,5])

In [17]:
rev_arr = np.flip(arr8) 

In [18]:
arr8

array([1, 2, 3, 4, 5])

In [19]:
rev_arr

array([5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
arr9 = np.arange(0,9).reshape(3,3)

In [21]:
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [22]:
arr10=np.array ([1,2,0,0,4,0])

In [23]:
arr10

array([1, 2, 0, 0, 4, 0])

In [24]:
non_zero = np.nonzero(arr10)[0]

In [25]:
non_zero

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
arr11 = np.eye(3,3)

In [27]:
arr11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
arr12 = np.random.rand(3,3,3)

In [29]:
arr12

array([[[0.03650979, 0.55279646, 0.07361857],
        [0.53815611, 0.24662919, 0.00411493],
        [0.8185931 , 0.27532401, 0.5773601 ]],

       [[0.7503308 , 0.6702345 , 0.50317433],
        [0.69690725, 0.13611932, 0.32928967],
        [0.42613852, 0.88380408, 0.4792494 ]],

       [[0.64560062, 0.2533173 , 0.20276423],
        [0.64263653, 0.62348844, 0.78210351],
        [0.02914636, 0.70588732, 0.31237137]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
arr13 = np.random.rand(10,10)

In [31]:
arr13

array([[0.43895584, 0.0120155 , 0.51935174, 0.39122349, 0.7227728 ,
        0.03957623, 0.57378209, 0.94695054, 0.01831083, 0.9282981 ],
       [0.93304953, 0.34778428, 0.44257213, 0.10121121, 0.19151928,
        0.00197093, 0.4177352 , 0.10517807, 0.50040866, 0.19033928],
       [0.43573895, 0.92677112, 0.24920546, 0.54159373, 0.47722363,
        0.80552583, 0.3205194 , 0.20864963, 0.56669264, 0.52802058],
       [0.34701308, 0.15999496, 0.37597258, 0.28063921, 0.43708623,
        0.77939624, 0.08613974, 0.84466243, 0.51562259, 0.8354739 ],
       [0.89278867, 0.68395612, 0.25198357, 0.56129452, 0.20782817,
        0.64405984, 0.93313648, 0.61218707, 0.2756824 , 0.51733365],
       [0.80012139, 0.79922749, 0.46290749, 0.0526341 , 0.58850397,
        0.43651127, 0.09983524, 0.99805394, 0.30041376, 0.04220699],
       [0.50467596, 0.70440808, 0.52172117, 0.60788683, 0.55499714,
        0.43944136, 0.49096913, 0.4517926 , 0.1246501 , 0.0393996 ],
       [0.1091972 , 0.8084519 , 0.1028118

In [32]:
arr13.max()

0.9980539430217041

In [33]:
arr13.min()

0.00197092565304291

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
arr14 = np.random.rand(30)

In [35]:
arr14

array([0.32463453, 0.94953605, 0.75334747, 0.51221203, 0.30027341,
       0.03099467, 0.9782715 , 0.06235852, 0.62948269, 0.20950213,
       0.67076818, 0.33477177, 0.74130962, 0.86107196, 0.62165451,
       0.02122363, 0.20680339, 0.13610028, 0.24970136, 0.26682051,
       0.61984888, 0.22722496, 0.44794703, 0.24555998, 0.2789949 ,
       0.58203033, 0.39206882, 0.26869179, 0.61962565, 0.87960911])

In [36]:
arr14_mean = np.mean(arr14)

In [37]:
arr14_mean

0.44741465541733977

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
arr15 = np.ones((3,3))

In [39]:
arr15

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
arr15 [1:-1,1:-1]=[0]

In [41]:
arr15

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [42]:
arr16 = np.full([3,3],42)

In [43]:
arr16

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [44]:
arr16= np.pad(arr16, pad_width=1, mode='constant', constant_values=0)

In [45]:
arr16

array([[ 0,  0,  0,  0,  0],
       [ 0, 42, 42, 42,  0],
       [ 0, 42, 42, 42,  0],
       [ 0, 42, 42, 42,  0],
       [ 0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [47]:
arr18 = np.zeros((5,5))

In [48]:
arr18

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.fill_diagonal(arr18[1:], [1,2,3,4])

In [50]:
arr18

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [51]:
arr19 = np.zeros((8,8),dtype=int)

In [52]:
arr19

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
arr19[::2,1::2]=1
arr19[1::2,::2]=1


In [54]:
arr19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

## The code np.unravel_index(99,(6,7,8)) is using the np.unravel_index() function from the NumPy library to convert a one-dimensional index into a multi-dimensional index for a given shape.

In [55]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

# NP.TILE(a,(x,y)) Function

## In NumPy Python, the tile() function is used to construct an array by repeating a given array a specified number of times. It takes two arguments - the first is the input array to be repeated, and the second is a tuple specifying the number of times each dimension of the input array should be repeated.

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [56]:
a = np.array([[1,0],[0,1]])

In [57]:
a

array([[1, 0],
       [0, 1]])

In [58]:
checkboard =np.tile(a,(4,4))

In [59]:
checkboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [60]:
# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

random_matrix

array([[0.41718952, 0.39108117, 0.0466858 , 0.87146081, 0.61666916],
       [0.87851723, 0.29118419, 0.91499081, 0.04951121, 0.86204771],
       [0.90074849, 0.63506624, 0.31095256, 0.41114144, 0.53698316],
       [0.3034201 , 0.20324132, 0.09738283, 0.56560117, 0.04049156],
       [0.65837519, 0.35209081, 0.40384861, 0.64040784, 0.39801759]])

In [61]:
# Calculate the norm of the matrix
norm = np.linalg.norm(random_matrix)

norm

2.7258865277287776

In [62]:
# Normalize the matrix
normalized_matrix = random_matrix / norm

print(normalized_matrix)


[[0.15304728 0.14346935 0.01712683 0.31969812 0.22622701]
 [0.3222868  0.10682183 0.33566724 0.01816334 0.3162449 ]
 [0.3304424  0.23297604 0.11407392 0.15082853 0.19699395]
 [0.11131061 0.07455971 0.0357252  0.20749256 0.01485446]
 [0.241527   0.12916562 0.14815313 0.23493562 0.146014  ]]


In [63]:
np.mean(random_matrix)

0.47188426131163763

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [64]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [65]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [66]:
# Define the custom dtype for a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

In [67]:
color_dtype

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [68]:
arr24_a = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12],
                   [13,14,15]])

In [69]:
arr24_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [70]:
arr24_b =np.array([[1,2],
                  [1,2],
                  [1,2]])

In [71]:
arr24_b

array([[1, 2],
       [1, 2],
       [1, 2]])

In [72]:
c = np.dot(arr24_a , arr24_b)

In [73]:
c

array([[ 6, 12],
       [15, 30],
       [24, 48],
       [33, 66],
       [42, 84]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [74]:
arr25 = np.array((1,2,3,4,5,6,7,8,9,10,11))

In [75]:
arr25

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
arr25[(arr25 > 3) & (arr25 < 8)] *= -1

In [77]:
arr25

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [78]:
print(sum(range(5),-1))

9


In [79]:
print(sum(range(5),-1))

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


In [82]:
np.array(0) / np.array(0)

/tmp/ipykernel_131285/873513115.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [83]:
np.array(0) // np.array(0)


/tmp/ipykernel_131285/474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [84]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [87]:
arr29 = np.random.uniform(-10,+10,10)

In [88]:
arr29

array([ 6.61877211,  0.49813167,  6.08845989,  8.19345416, -3.20836155,
       -7.95139926,  0.13030921,  7.97432776, -3.67202329,  0.6253391 ])

In [89]:
print (np.copysign(np.ceil(np.abs(arr29)), arr29))

[ 7.  1.  7.  9. -4. -8.  1.  8. -4.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

### intersect(n)d(a,b,c) function

In [91]:
arr30_a=([1,2,3,4])

In [92]:
arr30_a

[1, 2, 3, 4]

In [93]:
arr30_b = ([3,4,5,6])

In [94]:
arr30_b

[3, 4, 5, 6]

In [96]:
common=np.intersect1d(arr30_a,arr30_b)

In [97]:
common

array([3, 4])

In [98]:
arr30_c=([[1,2,],
          [3,4]])

In [99]:
arr30_c

[[1, 2], [3, 4]]

In [100]:
arr30_d = ([[5,2],
            [6,4]])

In [101]:
arr30_d

[[5, 2], [6, 4]]

In [102]:
np.intersect1d(arr30_c,arr30_d)

array([2, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

When NumPy takes the square root of a negative number, it returns a complex number with a positive real part and an imaginary part, represented by the constant 1j. For example:

On the other hand, np.emath.sqrt is a function that returns the complex square root of a number, even if the number is negative. Therefore, when np.emath.sqrt is called with -1 as an argument, it returns the complex number -1j.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [104]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [105]:
yesterday

numpy.datetime64('2023-03-01')

In [106]:
today

numpy.datetime64('2023-03-02')

In [107]:
tomorrow

numpy.datetime64('2023-03-03')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [108]:
arr34= np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [109]:
arr34

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')